version: 2.1
orbs:
  node: circleci/node@1.1.6
jobs:
  build:
    docker:
      - image: 'cimg/base:stable'
    steps:
      - checkout
      - run: 
          name: Install wget zip unzip curl
          command: |
            sudo apt install wget zip unzip curl -y
      - run:
          name: Install aws cli
          command: |
            curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
            unzip awscliv2.zip
            sudo ./aws/install -i /usr/local/aws-cli -b /usr/local/bin
            mkdir -p ~/.aws
            aws configure set default.region us-east-1
            aws configure set aws_access_key_id ${AWS_ACCESS_KEY_ID}
            aws configure set aws_secret_access_key ${AWS_SECRET_ACCESS_KEY}
            aws configure set aws_secret_access_key ${AWS_SECRET_ACCESS_KEY}
      - run: 
          name: Compress Artifacts
          command: |
            mkdir -p lambda_functions
            cd lambda_functions
            cp ../email.js .
            zip -r lambda-${CIRCLE_BUILD_NUM}.zip .
      - run:
          name: Upload Artifacts to S3
          command: |
            ls -la
            cd lambda_functions
            aws configure list
            aws s3 cp lambda-${CIRCLE_BUILD_NUM}.zip s3://${CODE_DEPLOY_S3_BUCKET} --sse
      - run:
          name: AWS Lambda Update Function Code
          command: |
            cd lambda_functions
            aws lambda update-function-code \
            --function-name  LamdaEmailFunc \
            --zip-file fileb://lambda-${CIRCLE_BUILD_NUM}.zip >/dev/null 2>&1
            # aws lambda update-function-code --function-name LamdaEmailFunc --region ${AWS_REGION} --zip-file fileb://lambda-${CIRCLE_BUILD_NUM}.zip
workflows:
    pr_check:
      jobs:
        - build